// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBahT-Of3K9Ndy1s0wFQFrGzvizG9Mrpbo',
    appId: '1:361484708239:web:9fbea9e4955057acea43fa',
    messagingSenderId: '361484708239',
    projectId: 'crudtutorial-bbf1c',
    authDomain: 'crudtutorial-bbf1c.firebaseapp.com',
    storageBucket: 'crudtutorial-bbf1c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2mpOI4bu5L7Ib15714qwIMcBJoi5FWSc',
    appId: '1:361484708239:android:1bee6ef597dc8293ea43fa',
    messagingSenderId: '361484708239',
    projectId: 'crudtutorial-bbf1c',
    storageBucket: 'crudtutorial-bbf1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN2EAaGnKVKY0Z6JedAhr4wjk3VHNl29A',
    appId: '1:361484708239:ios:97b14e6bff6f73c5ea43fa',
    messagingSenderId: '361484708239',
    projectId: 'crudtutorial-bbf1c',
    storageBucket: 'crudtutorial-bbf1c.appspot.com',
    iosBundleId: 'com.example.onlineDatabaseFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN2EAaGnKVKY0Z6JedAhr4wjk3VHNl29A',
    appId: '1:361484708239:ios:97b14e6bff6f73c5ea43fa',
    messagingSenderId: '361484708239',
    projectId: 'crudtutorial-bbf1c',
    storageBucket: 'crudtutorial-bbf1c.appspot.com',
    iosBundleId: 'com.example.onlineDatabaseFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBahT-Of3K9Ndy1s0wFQFrGzvizG9Mrpbo',
    appId: '1:361484708239:web:910270e6cfe68920ea43fa',
    messagingSenderId: '361484708239',
    projectId: 'crudtutorial-bbf1c',
    authDomain: 'crudtutorial-bbf1c.firebaseapp.com',
    storageBucket: 'crudtutorial-bbf1c.appspot.com',
  );
}
